### ISSUE TITLE
Memory leak in ettercap, ec_globals_alloc, src/ec_globals.c

### ISSUE THREAD

**Issue by 5hadowblad3** [Ettercap/ettercap#1201]
Hi, there.

There is a memory leak in ettercap in the newest main branch (8e1d6d800d7163a360a851bfedc1a4d793b14b2e).

To reproduce, compile with
~~~~
CFLAGS="-g -fsanitize=address"
~~~~
then run:
~~~~
./src/ettercap
~~~~

Here is the trace reported by ASAN:
~~~~
==1812145==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x4c3b37 in calloc  /dependence/llvm11/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x7f980abdabe3 in ec_globals_alloc  /benchmark/ettercap/src/ec_globals.c:46:4

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4c3b37 in calloc  /dependence/llvm11/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x7f980abdb06c in ec_globals_alloc  /benchmark/ettercap/src/ec_globals.c:55:4

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 2 allocation(s).
Aborted

~~~~

**Comment by LocutusOfBorg** [comment]
@5hadowblad3 hello, can you please test #1205?
